---
apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user
  namespace: service
spec:
  selector:
    matchLabels:
      type: service
      for: user
  # remove replica if using gitops
  replicas: 2
  template:
    metadata:
      labels:
        type: service
        for: user
    spec:
      containers:
        - name: user
          # image: { imageURI }
          image: nginx
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-products
  namespace: service
spec:
  selector:
    matchLabels:
      type: service
      for: products
  # remove replica if using gitops
  replicas: 2
  template:
    metadata:
      labels:
        type: service
        for: products
    spec:
      containers:
        - name: products
          image:
          # image: { imageURI }
          image: nginx
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
