---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hpa-user
  namespace: service
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hpa-product
  namespace: service
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  targetCPUUtilizationPercentage: 50
