---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hpa
  namespace: service
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hpa
  namespace: service
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  targetCPUUtilizationPercentage: 50
