---
apiVersion: v1
kind: Service
metadata:
  name: service-user
  namespace: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    for: user
    type: service
---
apiVersion: v1
kind: Service
metadata:
  name: service-product
  namespace: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    for: product
    type: service
